- name: NGINX
  hosts: nginx
  become: true
  vars:
    nginx_listen_port: 8080
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      tags: update-apt

    - name: Install NGINX package
      apt:
        name: nginx
        state: latest
      notify: restart nginx
      tags: nginx-package

    - name: Create NGINX config file from template
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: reload nginx
      tags: nginx-configuration

  handlers:
    - name: restart NGINX
      systemd:
        name: nginx
        state: restarted
        enabled: yes

    - name: Reload NGINX 
      systemd:
        name: nginx
        state: reloaded
  tags:
    - update-apt
    - nginx-package
    - nginx-configuration
